### ISSUE TITLE
알림 시 비정상 종료

### ISSUE THREAD

**Issue by ethan-223** [naccoro/WASK-Android#58]
알림이 울릴 시간에 이런 에러와 함께 비정상종료 되었습니다.
```
2020-08-16 17:59:33.517 24655-24655/com.naccoro.wask E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.naccoro.wask, PID: 24655
    java.lang.RuntimeException: Unable to start receiver com.naccoro.wask.receivers.AlarmReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.naccoro.wask/.notification.PushNotificationService (has extras) }: app is in background uid UidRecord{fb1ac58 u0a1275 RCVR bg:+1m12s441ms idle change:uncached procs:1 proclist:24655, seq(0,0,0)}
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:4225)
        at android.app.ActivityThread.access$1800(ActivityThread.java:273)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2116)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8125)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
     Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.naccoro.wask/.notification.PushNotificationService (has extras) }: app is in background uid UidRecord{fb1ac58 u0a1275 RCVR bg:+1m12s441ms idle change:uncached procs:1 proclist:24655, seq(0,0,0)}
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1688)
        at android.app.ContextImpl.startService(ContextImpl.java:1633)
        at android.content.ContextWrapper.startService(ContextWrapper.java:683)
        at android.content.ContextWrapper.startService(ContextWrapper.java:683)
        at com.naccoro.wask.receivers.AlarmReceiver.onReceive(AlarmReceiver.java:28)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:4216)
        at android.app.ActivityThread.access$1800(ActivityThread.java:273) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2116) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:8125) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100) 
```

**Comment by ethan-223** [comment]
https://parkho79.tistory.com/12
이것과 관련이 있을까요?

**Comment by jaeryo2357** [comment]
#77 에서 해결했습니다!
